# Generated by Django 5.2.4 on 2025-07-15 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('price', 'Price Inquiry'), ('test_drive', 'Test Drive Request'), ('financing', 'Financing Inquiry'), ('availability', 'Availability Check')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.vehiclelisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Inquiry',
                'verbose_name_plural': 'Listing Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_responses', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiries.listinginquiry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('alternate_date', models.DateField(blank=True, null=True)),
                ('alternate_time', models.TimeField(blank=True, null=True)),
                ('location_preference', models.CharField(blank=True, help_text='Preferred location for the test drive', max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_test_drives', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_details', to='inquiries.listinginquiry')),
            ],
            options={
                'ordering': ['preferred_date', 'preferred_time'],
            },
        ),
        migrations.AddIndex(
            model_name='listinginquiry',
            index=models.Index(fields=['status'], name='inquiries_l_status_2d1272_idx'),
        ),
        migrations.AddIndex(
            model_name='listinginquiry',
            index=models.Index(fields=['inquiry_type'], name='inquiries_l_inquiry_58b11a_idx'),
        ),
        migrations.AddIndex(
            model_name='listinginquiry',
            index=models.Index(fields=['is_read'], name='inquiries_l_is_read_264be9_idx'),
        ),
    ]
