# Generated by Django 5.2.7 on 2025-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinginquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
