# Generated by Django 5.2.4 on 2025-10-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listinginquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listinginquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiryresponse',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiries.listinginquiry'),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_test_drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_details', to='inquiries.listinginquiry'),
        ),
        migrations.AddIndex(
            model_name='listinginquiry',
            index=models.Index(fields=['status'], name='inquiries_l_status_2d1272_idx'),
        ),
        migrations.AddIndex(
            model_name='listinginquiry',
            index=models.Index(fields=['inquiry_type'], name='inquiries_l_inquiry_58b11a_idx'),
        ),
        migrations.AddIndex(
            model_name='listinginquiry',
            index=models.Index(fields=['is_read'], name='inquiries_l_is_read_264be9_idx'),
        ),
    ]
