# Generated by Django 5.2.4 on 2025-07-15 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified_pre_owned', 'Certified Pre-Owned')], default='used', max_length=20)),
                ('mileage', models.PositiveIntegerField(help_text='Vehicle mileage in kilometers')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('negotiable', 'Negotiable'), ('call', 'Call for Price')], default='fixed', max_length=20)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color_exterior', models.CharField(blank=True, max_length=50, null=True)),
                ('color_interior', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('warranty_information', models.TextField(blank=True, null=True)),
                ('additional_features', models.TextField(blank=True, null=True)),
                ('seller_notes', models.TextField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for SEO purposes', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Custom description for SEO purposes', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Keywords for SEO purposes', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('vehicle_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.vehiclespecification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status'], name='listings_ve_status_abad10_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['is_featured'], name='listings_ve_is_feat_639fee_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['is_premium'], name='listings_ve_is_prem_e59304_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['condition'], name='listings_ve_conditi_dd1a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['location_city', 'location_country'], name='listings_ve_locatio_84ac2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
