# Generated by Django 5.2.4 on 2025-10-16 07:30

import django.core.validators
import listings.models
import listings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Supported formats: JPEG, PNG, WebP, GIF. Max size: 10MB. Min dimensions: 400x300px', upload_to=listings.models.get_upload_path, validators=[listings.validators.FileSizeValidator(10), listings.validators.FileTypeValidator(['image/jpeg', 'image/png', 'image/webp', 'image/gif']), listings.validators.validate_image_dimensions, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/small/')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/medium/')),
                ('image_webp', models.ImageField(blank=True, null=True, upload_to='listings/webp/')),
                ('thumbnail_webp', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/webp/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Supported formats: MP4, MOV, AVI, WebM. Max size: 100MB', upload_to=listings.models.get_upload_path, validators=[listings.validators.FileSizeValidator(100), listings.validators.FileTypeValidator(['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm']), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/video_thumbnails/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Vehicle listing title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the vehicle')),
                ('price', models.DecimalField(decimal_places=2, help_text='Vehicle price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing discounts', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly payment', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.PositiveIntegerField(default=2020, help_text='Vehicle year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)])),
                ('trim', models.CharField(blank=True, help_text='Vehicle trim level', max_length=100, null=True)),
                ('kilometers', models.PositiveIntegerField(default=0, help_text='Vehicle mileage in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Mileage in miles', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(blank=True, help_text='Vehicle location', max_length=255, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified_pre_owned', 'Certified Pre-Owned')], default='used', help_text='Vehicle condition', max_length=20)),
                ('stock_number', models.CharField(blank=True, help_text='Vehicle stock number', max_length=50, null=True)),
                ('is_luxury', models.BooleanField(default=False, help_text='Is this a luxury vehicle')),
                ('is_certified', models.BooleanField(default=False, help_text='Is this a certified vehicle')),
                ('exterior_color', models.CharField(default='White', help_text='Vehicle exterior color', max_length=50)),
                ('interior_color', models.CharField(blank=True, help_text='Interior color', max_length=50, null=True)),
                ('engine_type', models.CharField(blank=True, help_text='Engine type description', max_length=100, null=True)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, help_text='Engine size in liters', max_digits=4, null=True)),
                ('horsepower', models.PositiveIntegerField(blank=True, help_text='Engine horsepower', null=True)),
                ('torque', models.PositiveIntegerField(blank=True, help_text='Engine torque in lb-ft', null=True)),
                ('drivetrain', models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', '4-Wheel Drive')], help_text='Drivetrain type', max_length=20, null=True)),
                ('fuel_economy_city', models.PositiveIntegerField(blank=True, help_text='City MPG', null=True)),
                ('fuel_economy_highway', models.PositiveIntegerField(blank=True, help_text='Highway MPG', null=True)),
                ('acceleration_0_60', models.DecimalField(blank=True, decimal_places=1, help_text='0-60 mph time in seconds', max_digits=4, null=True)),
                ('top_speed', models.PositiveIntegerField(blank=True, help_text='Top speed in mph', null=True)),
                ('towing_capacity', models.PositiveIntegerField(blank=True, help_text='Towing capacity in lbs', null=True)),
                ('curb_weight', models.PositiveIntegerField(blank=True, help_text='Curb weight in lbs', null=True)),
                ('safety_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Safety rating out of 5', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seating_capacity', models.PositiveIntegerField(blank=True, help_text='Number of seats', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Admin feedback for rejected listings', null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(default='UAE', max_length=100)),
                ('warranty_information', models.TextField(blank=True, null=True)),
                ('additional_features', models.TextField(blank=True, null=True)),
                ('seller_notes', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for SEO purposes', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Custom description for SEO purposes', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Keywords for SEO purposes', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dealer name', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Dealer logo', null=True, upload_to='dealers/logos/')),
                ('description', models.TextField(blank=True, help_text='Dealer description', null=True)),
                ('address', models.TextField(help_text='Dealer address')),
                ('phone', models.CharField(help_text='Dealer phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Dealer email', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Dealer website', null=True)),
                ('hours', models.CharField(default='Open until 9:00 PM', help_text='Business hours', max_length=255)),
                ('license_number', models.CharField(blank=True, help_text='Dealer license number', max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Number of reviews')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='UAE', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='listings_de_is_acti_abb096_idx'), models.Index(fields=['is_verified'], name='listings_de_is_veri_1dc3bb_idx'), models.Index(fields=['city', 'country'], name='listings_de_city_f4dac0_idx')],
            },
        ),
    ]
