# Generated by Django 5.2.4 on 2025-10-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='body_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle body type/category (e.g., Sedan, SUV, Hatchback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vehicles.vehiclecategory'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.dealer'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.fueltype'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.brand'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.transmissiontype'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listingvideo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listingstatuslog',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.vehiclelisting'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status'], name='listings_ve_status_abad10_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['is_featured'], name='listings_ve_is_feat_639fee_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['is_premium'], name='listings_ve_is_prem_e59304_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['condition'], name='listings_ve_conditi_dd1a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['fuel_type'], name='listings_ve_fuel_ty_893bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['transmission'], name='listings_ve_transmi_c18a12_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['body_type'], name='listings_ve_body_ty_11810b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['make', 'model'], name='listings_ve_make_id_2f9cec_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['year'], name='listings_ve_year_2f6127_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['price'], name='listings_ve_price_937816_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['kilometers'], name='listings_ve_kilomet_a3a59d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['location_city', 'location_country'], name='listings_ve_locatio_84ac2b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['created_at'], name='listings_ve_created_a4022c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['published_at'], name='listings_ve_publish_42a43f_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlisting',
            index=models.Index(fields=['user', 'created_at'], name='listings_sa_user_id_a0e56a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlisting',
            index=models.Index(fields=['listing'], name='listings_sa_listing_613f4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', 'created_at'], name='listings_li_listing_f1156a_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['user', 'created_at'], name='listings_li_user_id_2d0ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['ip_address', 'created_at'], name='listings_li_ip_addr_1eed65_idx'),
        ),
        migrations.AddIndex(
            model_name='listingvideo',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_cb5228_idx'),
        ),
        migrations.AddIndex(
            model_name='listingstatuslog',
            index=models.Index(fields=['listing', 'timestamp'], name='listings_li_listing_6a47f0_idx'),
        ),
        migrations.AddIndex(
            model_name='listingstatuslog',
            index=models.Index(fields=['changed_by', 'timestamp'], name='listings_li_changed_ac4493_idx'),
        ),
        migrations.AddIndex(
            model_name='listingstatuslog',
            index=models.Index(fields=['new_status', 'timestamp'], name='listings_li_new_sta_ec0a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'is_primary'], name='listings_li_listing_0a94a7_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_5fba7f_idx'),
        ),
    ]
