# Generated by Django 5.2.7 on 2025-10-09 00:24

import django.core.validators
import django.db.models.deletion
import listings.models
import listings.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Supported formats: MP4, MOV, AVI, WebM. Max size: 100MB', upload_to=listings.models.get_upload_path, validators=[listings.validators.FileSizeValidator(100), listings.validators.FileTypeValidator(['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm']), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/video_thumbnails/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['-is_primary', 'order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='listingview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='listingview',
            old_name='viewed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='savedlisting',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='color_exterior',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='vehicle_specification',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingview',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='color',
            field=models.CharField(default='White', help_text='Vehicle color', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='engine_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Engine size in liters', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in Hybrid'), ('lpg', 'LPG'), ('cng', 'CNG')], default='gasoline', help_text='Vehicle fuel type', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='kilometers',
            field=models.PositiveIntegerField(default=0, help_text='Vehicle mileage in kilometers', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='make',
            field=models.CharField(default='Unknown', help_text='Vehicle make/brand', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='model',
            field=models.CharField(default='Unknown', help_text='Vehicle model', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin feedback for rejected listings', null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic')], default='manual', help_text='Vehicle transmission type', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='year',
            field=models.PositiveIntegerField(default=2020, help_text='Vehicle year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(help_text='Supported formats: JPEG, PNG, WebP, GIF. Max size: 10MB. Min dimensions: 400x300px', upload_to=listings.models.get_upload_path, validators=[listings.validators.FileSizeValidator(10), listings.validators.FileTypeValidator(['image/jpeg', 'image/png', 'image/webp', 'image/gif']), listings.validators.validate_image_dimensions, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='listingview',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified_pre_owned', 'Certified Pre-Owned')], default='used', help_text='Vehicle condition', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='description',
            field=models.TextField(help_text='Detailed description of the vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='location_country',
            field=models.CharField(default='UAE', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Vehicle price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='title',
            field=models.CharField(help_text='Vehicle listing title', max_length=255),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'is_primary'], name='listings_li_listing_0a94a7_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_5fba7f_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', 'created_at'], name='listings_li_listing_f1156a_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['user', 'created_at'], name='listings_li_user_id_2d0ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['ip_address', 'created_at'], name='listings_li_ip_addr_1eed65_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlisting',
            index=models.Index(fields=['user', 'created_at'], name='listings_sa_user_id_a0e56a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlisting',
            index=models.Index(fields=['listing'], name='listings_sa_listing_613f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['fuel_type'], name='listings_ve_fuel_ty_c4ac24_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['transmission'], name='listings_ve_transmi_0de9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['make', 'model'], name='listings_ve_make_5299ff_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['year'], name='listings_ve_year_2f6127_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['price'], name='listings_ve_price_937816_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['kilometers'], name='listings_ve_kilomet_a3a59d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['created_at'], name='listings_ve_created_a4022c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['published_at'], name='listings_ve_publish_42a43f_idx'),
        ),
        migrations.AddField(
            model_name='listingvideo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.vehiclelisting'),
        ),
        migrations.AddIndex(
            model_name='listingvideo',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_cb5228_idx'),
        ),
    ]
