# Generated by Django 5.2.7 on 2025-10-09 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingvideo_alter_listingimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['listing', 'timestamp'], name='listings_li_listing_6a47f0_idx'), models.Index(fields=['changed_by', 'timestamp'], name='listings_li_changed_ac4493_idx'), models.Index(fields=['new_status', 'timestamp'], name='listings_li_new_sta_ec0a5c_idx')],
            },
        ),
    ]
