# Generated by Django 5.2.4 on 2025-10-19 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_is_feat_639fee_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_is_prem_e59304_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_conditi_dd1a9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_fuel_ty_893bd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_transmi_c18a12_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_body_ty_11810b_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_make_id_2f9cec_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_year_2f6127_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_price_937816_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_kilomet_a3a59d_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_locatio_84ac2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_created_a4022c_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelisting',
            name='listings_ve_publish_42a43f_idx',
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'is_featured'], name='listings_ve_status_e992b9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'is_premium'], name='listings_ve_status_bc525d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'published_at'], name='listings_ve_status_714ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['make', 'model', 'year'], name='listings_ve_make_id_1ac07b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['make', 'status'], name='listings_ve_make_id_5a153f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['condition', 'status'], name='listings_ve_conditi_7acef3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['fuel_type', 'status'], name='listings_ve_fuel_ty_72f69a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['transmission', 'status'], name='listings_ve_transmi_060a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['body_type', 'status'], name='listings_ve_body_ty_249234_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['price', 'status'], name='listings_ve_price_4a0b90_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['year', 'status'], name='listings_ve_year_504ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['kilometers', 'status'], name='listings_ve_kilomet_7660bd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['location_city', 'location_country', 'status'], name='listings_ve_locatio_e8ff76_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['location_city', 'status'], name='listings_ve_locatio_260253_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['created_at', 'status'], name='listings_ve_created_baf937_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['published_at', 'status'], name='listings_ve_publish_9199d4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['views_count', 'status'], name='listings_ve_views_c_0551ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['user', 'status'], name='listings_ve_user_id_b65b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['dealer', 'status'], name='listings_ve_dealer__1a9748_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'is_featured', 'created_at'], name='listings_ve_status_97ba77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'price', 'year'], name='listings_ve_status_e7b0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['make', 'model', 'year', 'status'], name='listings_ve_make_id_d20f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['title'], name='listings_ve_title_d6b5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['slug'], name='listings_ve_slug_c4ae26_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelisting',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelisting',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900)), name='valid_year'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelisting',
            constraint=models.CheckConstraint(condition=models.Q(('kilometers__gte', 0)), name='positive_kilometers'),
        ),
    ]
