# Generated by Django 5.2.4 on 2025-10-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_vehiclelisting_status_listingstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/webp/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/medium/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/small/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/webp/'),
        ),
    ]
