# Generated by Django 5.2.4 on 2025-10-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage_image_webp_and_more'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='body_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle body type/category (e.g., Sedan, SUV, Hatchback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vehicles.vehiclecategory'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['body_type'], name='listings_ve_body_ty_11810b_idx'),
        ),
    ]
