# Generated by Django 5.2.4 on 2025-10-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdashboardpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwidgetsetting',
            name='user_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.userdashboardpreference'),
        ),
        migrations.AddField(
            model_name='userwidgetsetting',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.dashboardwidget'),
        ),
        migrations.AddField(
            model_name='userdashboardpreference',
            name='widgets',
            field=models.ManyToManyField(through='admin_panel.UserWidgetSetting', to='admin_panel.dashboardwidget'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type'], name='admin_panel_action__e50e76_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_time'], name='admin_panel_action__24e817_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='admin_panel_user_id_c3e782_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwidgetsetting',
            unique_together={('user_preference', 'widget')},
        ),
    ]
