# Generated by Django 5.2.4 on 2025-10-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('listings', '0002_initial'),
        ('reviews', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerreview',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingreview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listingreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='dealer_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.dealerreview'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='listing_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.listingreview'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='dealer_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.dealerreview'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='listing_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.listingreview'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='Admin user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_review_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='dealer_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.dealerreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='listing_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.listingreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='seller_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.sellerreview'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='seller_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.sellerreview'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='seller_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.sellerreview'),
        ),
        migrations.AddField(
            model_name='vehiclereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclereview',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='vehicle_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.vehiclereview'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='vehicle_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.vehiclereview'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='vehicle_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.vehiclereview'),
        ),
        migrations.AddIndex(
            model_name='dealerreview',
            index=models.Index(fields=['status'], name='reviews_dea_status_c070e6_idx'),
        ),
        migrations.AddIndex(
            model_name='dealerreview',
            index=models.Index(fields=['overall_rating'], name='reviews_dea_overall_e051e7_idx'),
        ),
        migrations.AddIndex(
            model_name='dealerreview',
            index=models.Index(fields=['is_verified_transaction'], name='reviews_dea_is_veri_f168ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealerreview',
            unique_together={('user', 'dealer')},
        ),
        migrations.AddIndex(
            model_name='listingreview',
            index=models.Index(fields=['status'], name='reviews_lis_status_2b97c1_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreview',
            index=models.Index(fields=['overall_rating'], name='reviews_lis_overall_157a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreview',
            index=models.Index(fields=['is_verified_purchase'], name='reviews_lis_is_veri_f7c347_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingreview',
            unique_together={('user', 'listing')},
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['action'], name='reviews_rev_action_2331a2_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['content_type', 'object_id'], name='reviews_rev_content_27a117_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user'], name='reviews_rev_user_id_54c9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['admin_user'], name='reviews_rev_admin_u_619445_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_6f18ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['status'], name='reviews_sel_status_ed0191_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['overall_rating'], name='reviews_sel_overall_ea2ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['is_verified_transaction'], name='reviews_sel_is_veri_aacec9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together={('user', 'seller')},
        ),
        migrations.AddIndex(
            model_name='vehiclereview',
            index=models.Index(fields=['status'], name='reviews_veh_status_ad4d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereview',
            index=models.Index(fields=['overall_rating'], name='reviews_veh_overall_d05952_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereview',
            index=models.Index(fields=['is_verified_owner'], name='reviews_veh_is_veri_5a460e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclereview',
            unique_together={('user', 'vehicle_model', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('user', 'dealer_review'), ('user', 'listing_review'), ('user', 'seller_review'), ('user', 'vehicle_review')},
        ),
    ]
