# Generated by Django 5.2.4 on 2025-10-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='related_brands',
            field=models.ManyToManyField(blank=True, related_name='articles', to='vehicles.brand'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_vehicle_models',
            field=models.ManyToManyField(blank=True, related_name='articles', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.contentcategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='content.contentcategory'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='content.contentcategory'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='related_brands',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='vehicles.brand'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='related_vehicle_models',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.mediagallery'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.page'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='content.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.tag'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='content_art_status_e667c8_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='content_art_is_feat_f4f830_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='content_art_publish_09f985_idx'),
        ),
    ]
